GET http://localhost:3002/customers/

###
GET http://localhost:3002/customers/1
###
POST http://localhost:3002/customers
Content-Type: application/json

{
	"firstname":"mwas3",
	"lastname": "vic",
    "username":"mwas3vic",
	"email":"mwas3vic@gmail.com",
	"password":"Kami1234"
}

###
PUT http://localhost:3002/customers/3
Content-Type: application/json

{

	"account_balance":"100"
}

###
DELETE  http://localhost:3002/customers/2