GET http://localhost:3002/customers/


###
GET http://localhost:3002/customers/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im13YXMxdmljIiwiaWQiOjEsImlhdCI6MTczMjU2ODc2OSwiZXhwIjoxNzMyNTY4Nzg0fQ.BOsk0XRW9fqsagplCT5LKP4C7RTZbHAPA0zFMb8sho4
###
POST http://localhost:3002/customers
Content-Type: application/json

{
	"firstname":"mwas1",
	"lastname": "vic",
    "username":"mwas1vic",
	"email":"mwas1vic@gmail.com",
	"password":"Kami1234"
}

###
PUT http://localhost:3002/customers/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im13YXMxdmljIiwiaWQiOjEsImlhdCI6MTczMjU2ODc2OSwiZXhwIjoxNzMyNTY4Nzg0fQ.BOsk0XRW9fqsagplCT5LKP4C7RTZbHAPA0zFMb8sho4
Content-Type: application/json

{

	"account_balance":"1"
}

###
DELETE  http://localhost:3002/customers/2

###
POST http://localhost:3002/auth/login
Content-Type: application/json

{
  "username": "mwas1vic",
  "password":"Kami1234"

}

###

POST http://localhost:3002/auth/refresh-token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}